services:
  postgresql_master:
    image: arxi0xyz/arxi-cloud-native-lab_postgresql-master:main
    container_name: postgresql_master
    ports: 
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}  
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - './data:/var/lib/postgresql/data'