on:
  push:
    branches:
      - main
    tags:
      - 'v*'  
  pull_request:
    branches:
      - main
    types:
      - closed
  release:
    types: [published] 

jobs:
  # Dev
  build-dev-image:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: arxi0xyz/arxi-cloud-native-lab_postgresql-master
          tags: dev-${{ github.sha }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=arxi0xyz/arxi-cloud-native-lab_postgresql-master:buildcache
          cache-to: type=registry,ref=arxi0xyz/arxi-cloud-native-lab_postgresql-master:buildcache,mode=max

  
  build-prod-image:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: arxi0xyz/arxi-cloud-native-lab_postgresql-master
          tags: ${{ github.ref_name }},latest

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=arxi0xyz/arxi-cloud-native-lab_postgresql-master:buildcache
          cache-to: type=registry,ref=arxi0xyz/arxi-cloud-native-lab_postgresql-master:buildcache,mode=max